// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdyeqVpdALbbtUyJ6MnUQr9cZC7h6rXSE',
    appId: '1:566329715974:web:2e26343cae449c61f78287',
    messagingSenderId: '566329715974',
    projectId: 'eac-app-admin-47662',
    authDomain: 'eac-app-admin-47662.firebaseapp.com',
    storageBucket: 'eac-app-admin-47662.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4YCWJKBSRkJrm7SnwVQ1TZxI9AI3Qb2c',
    appId: '1:566329715974:android:6b07ba074da0d523f78287',
    messagingSenderId: '566329715974',
    projectId: 'eac-app-admin-47662',
    storageBucket: 'eac-app-admin-47662.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAhDxcTJuPYd6ajoeGt7ReO1Uj0d6qmBE',
    appId: '1:566329715974:ios:b3406aa07439dd4ef78287',
    messagingSenderId: '566329715974',
    projectId: 'eac-app-admin-47662',
    storageBucket: 'eac-app-admin-47662.appspot.com',
    iosClientId: '566329715974-pr80e96gb3b0o8beh0eaqlajo1f317si.apps.googleusercontent.com',
    iosBundleId: 'com.epower.eacappAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAhDxcTJuPYd6ajoeGt7ReO1Uj0d6qmBE',
    appId: '1:566329715974:ios:b3406aa07439dd4ef78287',
    messagingSenderId: '566329715974',
    projectId: 'eac-app-admin-47662',
    storageBucket: 'eac-app-admin-47662.appspot.com',
    iosClientId: '566329715974-pr80e96gb3b0o8beh0eaqlajo1f317si.apps.googleusercontent.com',
    iosBundleId: 'com.epower.eacappAdmin',
  );
}
